const schema = { meta:{ name:'', variant:'川麻·血战到底', version:'v1', description:'' }, table:{ players:4, handSize:13, tiles:{ suits:['万','筒','条'], includeWinds:false, includeDragons:false, includeFlowers:false, totalTiles:108 } }, dealer:{ continuousDealer:true, dealerBonus:{ selfDrawAddBase:1, winAddBase:1 } }, settlement:{ payMode:'三家付', basePoint:1, cap:0 }, birds:{ enabled:true, count:2, hitBonus:1 }, penalties:{ checkNoDeclare:true, checkWrongSuit:true }, scoring:{ baseHands:[ {key:'平胡',fan:1}, {key:'自摸',fan:1}, {key:'对对胡',fan:2}, {key:'清一色',fan:4} ], melds:[ {key:'明杠',fan:1}, {key:'暗杠',fan:2} ], extras:[ {key:'绝张',fan:1} ] } }
function renderTemplateMarkdown(rule){ const r = { ...schema, ...rule }; const m=r.meta||{}, t=r.table||{}, tiles=t.tiles||{}, d=r.dealer||{}, s=r.settlement||{}, b=r.birds||{}, p=r.penalties||{}, sc=r.scoring||{}; const list = arr=> (arr||[]).map(i=> `- ${i.key}：${i.fan}番`).join('\n') || '- 无'; return [ `# ${m.name}`, '', `> 变体：${m.variant} · 版本：${m.version}`, '', '## 说明', `${m.description || '无'}`, '', '## 桌面', `- 人数：${t.players}`, `- 手牌数：${t.handSize}`, `- 牌组：${tiles.totalTiles || ''}张（${tiles.suits.join('、')}${tiles.includeWinds?'·含风':''}${tiles.includeDragons?'·含箭':''}${tiles.includeFlowers?'·含花':''}）`, '', '## 庄家', `- 连庄：${d.continuousDealer ? '是' : '否'}`, `- 自摸加底：${d.dealerBonus?.selfDrawAddBase || 0}`, `- 胡牌加底：${d.dealerBonus?.winAddBase || 0}`, '', '## 结算', `- 付费模式：${s.payMode}`, `- 底分：${s.basePoint}`, `- 封顶：${s.cap ? s.cap+'番' : '不限'}`, '', '## 抓鸟', `- 开启：${b.enabled ? '是' : '否'}`, `- 数量：${b.count || 0}`, `- 每中一鸟加底：${b.hitBonus || 0}`, '', '## 违例检查', `- 查大叫：${p.checkNoDeclare ? '是' : '否'}`, `- 查花猪：${p.checkWrongSuit ? '是' : '否'}`, '', '## 番型', '### 基础番型', `${list(sc.baseHands)}`, '### 杠类加番', `${list(sc.melds)}`, '### 额外加成', `${list(sc.extras)}` ].join('\n') }
function parseNaturalLanguage(nl){ const r = JSON.parse(JSON.stringify(schema)); const text = (nl||'').replace(/\s+/g,''); const m=text.match(/抓(\d+)鸟/); if(m) r.birds.enabled=true, r.birds.count=Number(m[1]); const h=text.match(/手牌(\d+)张?/); if(h) r.table.handSize=Number(h[1]); if(/三家付/.test(text)) r.settlement.payMode='三家付'; if(/一人付/.test(text)) r.settlement.payMode='一人付'; if(/血战到底/.test(text)) r.meta.variant='川麻·血战到底'; if(/血流成河/.test(text)) r.meta.variant='川麻·血流成河'; const b=text.match(/每中一鸟加(\d+)/); if(b) r.birds.hitBonus=Number(b[1]); const dp=text.match(/底分(\d+)/); if(dp) r.settlement.basePoint=Number(dp[1]); return r }
const presetChuanMaXueZhan = { id:'preset-chuanma-xuezhan', name:'川麻·血战到底（模版）', desc:'常见川麻血战到底基线规则，可编辑微调', version:'v1', preset:true, schema, rule:{ meta:{ name:'川麻·血战到底', variant:'川麻·血战到底', version:'v1', description:'四人，无风无箭无花；连庄；抓鸟2，每中一鸟加1；查花猪/查大叫；示例番型含清一色、对对胡等' }, table:{ players:4, handSize:13, tiles:{ suits:['万','筒','条'], includeWinds:false, includeDragons:false, includeFlowers:false, totalTiles:108 } }, dealer:{ continuousDealer:true, dealerBonus:{ selfDrawAddBase:1, winAddBase:1 } }, settlement:{ payMode:'三家付', basePoint:1, cap:0 }, birds:{ enabled:true, count:2, hitBonus:1 }, penalties:{ checkNoDeclare:true, checkWrongSuit:true }, scoring:{ baseHands:[ {key:'平胡',fan:1}, {key:'自摸',fan:1}, {key:'对对胡',fan:2}, {key:'清一色',fan:4} ], melds:[ {key:'明杠',fan:1}, {key:'暗杠',fan:2} ], extras:[ {key:'绝张',fan:1} ] } }, templateMarkdown: '' }
presetChuanMaXueZhan.templateMarkdown = renderTemplateMarkdown(presetChuanMaXueZhan.rule)
function validateRuleObject(r){ const ok = r && r.table && r.table.players && r.table.handSize && r.scoring && Array.isArray(r.scoring.baseHands); return !!ok }
function validateMarkdown(md){ const required = ['## 桌面','## 庄家','## 结算','## 抓鸟','## 违例检查','## 番型']; return required.every(k=> md.includes(k)) }
function buildRuleObject(metaName, nlText){ const r = parseNaturalLanguage(nlText); r.meta.name = metaName || r.meta.name; if(!validateRuleObject(r)) throw new Error('规则不完整：缺少关键字段'); const md = renderTemplateMarkdown(r); if(!validateMarkdown(md)) throw new Error('Markdown 模版不符合规范'); return { id:'rule-'+Date.now(), name: metaName || r.meta.name, desc:'', version: r.meta.version, schema, rule: r, templateMarkdown: md } }
module.exports = { schema, renderTemplateMarkdown, parseNaturalLanguage, presetChuanMaXueZhan, buildRuleObject, validateRuleObject, validateMarkdown }
